# Generated by Django 5.2.15 on 2026-07-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.FloatField(max_length=10)),
                ('description', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
