# Generated by Django 5.2.15 on 2026-07-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_expenseuser_expense_created_at_expense_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Bills', 'Bills'), ('Health', 'Health'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], default='Other', max_length=30),
        ),
    ]
