# Generated by Django 5.2.15 on 2026-07-13 07:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.FloatField()),
                ('monthly_saving_goal', models.FloatField()),
                ('yearly_saving_goal', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_goal', to='expense.expenseuser')),
            ],
        ),
    ]
